version: '3.11.9'
services:
# docker run -d -p 5000:5000 --env HELLO_HOST=http://hello-app --name=books --network=hello-net  helloapp:0.1
  helloapp:
    image: helloapp:0.1
    ports:
      - "5000:5000"
    restart: always
    # environment:
    #   HELLO_HOST: http://hello-app
    networks:
      - hello-comp-net

networks:
  hello-comp-net: